# Generated by Django 4.2.10 on 2026-04-30 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecole', '0001_initial'),
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierInscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('parent_nom', models.CharField(max_length=100)),
                ('parent_prenom', models.CharField(max_length=100)),
                ('parent_telephone', models.CharField(max_length=20)),
                ('parent_telephone_secondaire', models.CharField(blank=True, max_length=20)),
                ('parent_email', models.EmailField(blank=True, max_length=254)),
                ('parent_adresse', models.TextField(blank=True)),
                ('parent_profession', models.CharField(blank=True, max_length=100)),
                ('parent_lien', models.CharField(default='Parent', max_length=50)),
                ('acte_naissance', models.BooleanField(default=False)),
                ('certificat_scolarite', models.BooleanField(default=False)),
                ('photo_fournie', models.BooleanField(default=False)),
                ('carnet_sante', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('ASPIRANT', 'Aspirant'), ('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REJETE', 'Rejeté'), ('ANNULE', 'Annulé')], default='ASPIRANT', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True)),
                ('motif_rejet', models.TextField(blank=True)),
                ('classe_souhaitee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers', to='ecole.classe')),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_crees', to=settings.AUTH_USER_MODEL)),
                ('eleve_cree', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossier_origine', to='eleves.eleve')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dossiers_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Dossier d'inscription",
                'ordering': ['-date_creation'],
            },
        ),
    ]
