# Generated by Django 4.2.10 on 2026-05-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=80)),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='eleves.parenteleve')),
            ],
            options={
                'verbose_name': 'Consultation parent',
                'ordering': ['-date_consultation'],
            },
        ),
    ]
