# Generated by Django 4.2.10 on 2026-04-30 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eleves', '0001_initial'),
        ('ecole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre')], max_length=2)),
                ('type_evaluation', models.CharField(choices=[('DEVOIR', 'Devoir'), ('COMPOSITION', 'Composition'), ('INTERROGATION', 'Interrogation'), ('EXAMEN', 'Examen')], max_length=20)),
                ('note', models.DecimalField(decimal_places=2, max_digits=5)),
                ('note_sur', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('date_evaluation', models.DateField()),
                ('observations', models.TextField(blank=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='eleves.eleve')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='ecole.matiere')),
                ('saisie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'ordering': ['trimestre', 'matiere', 'date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trimestre', models.CharField(choices=[('T1', '1er Trimestre'), ('T2', '2ème Trimestre'), ('T3', '3ème Trimestre')], max_length=2)),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('moyenne_generale', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('rang', models.PositiveIntegerField(null=True)),
                ('effectif_classe', models.PositiveIntegerField(null=True)),
                ('appreciation', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('genere_le', models.DateTimeField(auto_now=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletins', to='eleves.eleve')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins_valides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulletin',
                'unique_together': {('eleve', 'trimestre', 'annee_scolaire')},
            },
        ),
    ]
