# Generated by Django 4.2.10 on 2026-04-30 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('telephone', models.CharField(max_length=20)),
                ('telephone_secondaire', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.TextField(blank=True)),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('lien_parente', models.CharField(default='Parent', max_length=50)),
                ('compte_utilisateur', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profil_parent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent / Tuteur',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(blank=True, max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/eleves/')),
                ('adresse', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('TRANSFERE', 'Transféré'), ('EXCLU', 'Exclu')], default='ACTIF', max_length=20)),
                ('date_inscription', models.DateField(auto_now_add=True)),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('observations', models.TextField(blank=True)),
                ('classe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='ecole.classe')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enfants', to='eleves.parenteleve')),
            ],
            options={
                'verbose_name': 'Élève',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
