# Generated by Django 4.2.10 on 2026-05-23 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecole', '0002_ecole_code_invitation'),
        ('messagerie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='destinataire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_recus', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ecole.ecole'),
        ),
        migrations.AlterField(
            model_name='message',
            name='classe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_classe', to='ecole.classe'),
        ),
        migrations.AlterField(
            model_name='message',
            name='destinataire_type',
            field=models.CharField(choices=[('prive', 'Privé'), ('classe', 'Classe'), ('tous', 'Tous les parents'), ('equipe', 'Équipe pédagogique'), ('direction', 'Direction'), ('comptabilite', 'Comptabilité')], default='prive', max_length=40),
        ),
    ]
