# Generated by Django 4.2.10 on 2026-04-30 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('statut', models.CharField(choices=[('PRESENT', 'Présent'), ('ABSENT', 'Absent'), ('RETARD', 'En retard'), ('EXCUSE', 'Absent excusé')], default='PRESENT', max_length=10)),
                ('motif', models.CharField(blank=True, max_length=200)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='eleves.eleve')),
                ('saisie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presences_saisies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Présence',
                'ordering': ['-date'],
                'unique_together': {('eleve', 'date')},
            },
        ),
    ]
