# Generated by Django 4.2.10 on 2026-05-13 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eleves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(blank=True, max_length=150)),
                ('isbn', models.CharField(blank=True, max_length=40)),
                ('editeur', models.CharField(blank=True, max_length=120)),
                ('annee', models.PositiveIntegerField(blank=True, null=True)),
                ('categorie', models.CharField(default='Autre', max_length=80)),
                ('stock_total', models.PositiveIntegerField(default=1)),
                ('stock_dispo', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Livre',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateField()),
                ('date_retour_prevue', models.DateField()),
                ('date_retour_reelle', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(default='EN_COURS', max_length=20)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='eleves.eleve')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprunts', to='bibliotheque.livre')),
            ],
            options={
                'verbose_name': 'Emprunt',
                'ordering': ['-date_emprunt'],
            },
        ),
    ]
