# Generated by Django 4.2.10 on 2026-04-30 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eleves', '0001_initial'),
        ('ecole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScolariteEleve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('montant_total', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PARTIEL', 'Partiel'), ('COMPLET', 'Complet')], default='EN_ATTENTE', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scolarites', to='eleves.eleve')),
            ],
            options={
                'verbose_name': 'Scolarité élève',
                'unique_together': {('eleve', 'annee_scolaire')},
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque')], default='ESPECES', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('date_paiement', models.DateField()),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('enregistre_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_enregistres', to=settings.AUTH_USER_MODEL)),
                ('scolarite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='comptabilite.scolariteeleve')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-date_paiement'],
            },
        ),
        migrations.CreateModel(
            name='DetailScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_du', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_paye', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('poste', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ecole.postescolarite')),
                ('scolarite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='comptabilite.scolariteeleve')),
            ],
            options={
                'unique_together': {('scolarite', 'poste')},
            },
        ),
    ]
