# Generated by Django 4.2.10 on 2026-04-30 22:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('directeur_nom', models.CharField(blank=True, max_length=200)),
                ('devise', models.CharField(default='FCFA', max_length=10)),
                ('annee_scolaire', models.CharField(default='2024-2025', max_length=9)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'École',
            },
        ),
        migrations.CreateModel(
            name='PosteScolarite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('obligatoire', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postes_scolarite', to='ecole.ecole')),
            ],
            options={
                'verbose_name': 'Poste de scolarité',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=10)),
                ('coefficient', models.PositiveIntegerField(default=1)),
                ('niveaux', models.JSONField(default=list)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='ecole.ecole')),
            ],
            options={
                'verbose_name': 'Matière',
                'ordering': ['nom'],
                'unique_together': {('ecole', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ConfigModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('DASHBOARD', 'Tableau de bord'), ('ELEVES', 'Élèves'), ('ENSEIGNANTS', 'Enseignants'), ('NOTES', 'Notes & Bulletins'), ('PRESENCES', 'Présences'), ('SECRETARIAT', 'Secrétariat'), ('PARAMETRES', 'Paramètres'), ('COMPTABILITE', 'Comptabilité'), ('EMPLOI_DU_TEMPS', 'Emploi du temps'), ('MESSAGERIE', 'Messagerie'), ('BIBLIOTHEQUE', 'Bibliothèque'), ('PORTAIL_PARENT', 'Portail parent')], max_length=50)),
                ('actif', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='ecole.ecole')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuration module',
                'unique_together': {('ecole', 'module')},
            },
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('CP1', 'CP1'), ('CP2', 'CP2'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2')], max_length=10)),
                ('nom', models.CharField(max_length=50)),
                ('effectif_max', models.PositiveIntegerField(default=40)),
                ('annee_scolaire', models.CharField(max_length=9)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='ecole.ecole')),
                ('enseignant_principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_principales', to='enseignants.enseignant')),
            ],
            options={
                'verbose_name': 'Classe',
                'ordering': ['niveau', 'nom'],
                'unique_together': {('ecole', 'nom', 'annee_scolaire')},
            },
        ),
    ]
