# Generated by Django 4.2.10 on 2026-05-23 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('cible_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('expire_le', models.DateTimeField(blank=True, null=True)),
                ('utilise', models.BooleanField(default=False)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='ecole.ecole')),
            ],
            options={
                'verbose_name': 'Invitation',
            },
        ),
    ]
