# Generated by Django 4.2.10 on 2026-05-24 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0002_ecole_code_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='is_demo',
            field=models.BooleanField(default=False, verbose_name='École de démonstration'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrateur'), ('TEACHER', 'Enseignant'), ('ACCOUNTANT', 'Comptable'), ('STUDENT', 'Élève')], default='STUDENT', max_length=20),
        ),
    ]
