# Generated by Django 4.2.10 on 2026-05-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0003_ecole_is_demo_invitation_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecole',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ecole',
            name='emails',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='ecole',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecoles/images/'),
        ),
        migrations.AddField(
            model_name='ecole',
            name='telephones',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='matiere',
            name='note_sur',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='classe',
            name='niveau',
            field=models.CharField(choices=[('CP1', 'CP1'), ('CP2', 'CP2'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CE', 'CE'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('CM', 'CM')], max_length=10),
        ),
    ]
