# Generated by Django 4.2.10 on 2026-05-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0004_ecole_description_ecole_emails_ecole_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='categorie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
